on:
  push:
    branches:
      - 'develop'
      - 'features/*'

name: Pre-Release App

jobs:
  Package_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: target/*.jar