on:
  push:
    tags:
      - '*'

name: Create Release of App

jobs:
  Package_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # we don't know what commit the last tag was
          fetch-depth: 0
      - run: git fetch --tags --force origin # WA: https://github.com/actions/checkout/issues/882
      - name: import GPG key
        run: |
          echo "${{ vars.GPG_PUBLIC_KEY }}" | gpg --import
          echo "${{ secrets.GPG_SECRET_KEY }}" | gpg --import --no-tty --batch --yes
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Run the Maven verify phase
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          AUTO_RELEASE_AFTER_CLOSE: true